- seed/articles.js
- server.js
Backend testing is complete. The backend is successfully connecting to mongodb and we are able to see JSON data in LOCAL host 3000
> GL backend testing

- client/src/components/Directions/Directions.jsx
This is the front-end in architecture before placing any code.
> Am feature

- client/src/App.js
- client/src/components/Buying/Buying.jsx
- client/src/components/ChatHomePage/ChatHomePage.jsx
- client/src/components/Directions/Directions.jsx
- client/src/components/HomeImage/HomeImage.jsx
- client/src/components/Options/Options.jsx
- client/src/components/shared/Footer/Footer.jsx
- client/src/components/shared/Nav/Nav.jsx
- client/src/screens/Home/Home.jsx
Added code to the home page components to render material onto the home screen!
> Added JSX code to all components for homepage screen to render material

- client/src/components/ChatHomePage/ChatHomePage.css
- client/src/components/ChatHomePage/ChatHomePage.jsx
Chat component is complete with respective css styled component
> completed the buildout and css for the chat home page component

- client/src/components/Directions/Directions.css
- client/src/components/Directions/Directions.jsx
- client/src/components/Options/Options.css
- client/src/components/Options/Options.jsx
We have small kinks to work out in relation to flex. Overall a solid rough draft.
> Options was styled and is nested in Directions which is also styled

- client/src/App.css
- client/src/components/shared/Nav.css
- client/src/components/shared/Nav/Nav.jsx
Made the header and most of the styling - missing the "login" logo and no breakpoints yet.
> DL - Header

- client/src/App.css
- client/src/components/ChatHomePage/ChatHomePage.css
- client/src/components/shared/Footer/Footer.css
- client/src/components/shared/Footer/Footer.jsx
Added icons and updated CSS styling for the footer
> Updated the Footer component with Icons and updated CSS styling

- client/src/components/HomeImage/HomeImage.css
- client/src/components/HomeImage/HomeImage.jsx
- client/src/screens/Home/Home.css
- client/src/screens/Home/Home.jsx
More to go, but getting there.
> Progress on Hero styling

- client/src/components/HomeImage/HomeImage.css
- client/src/components/HomeImage/HomeImage.jsx
Finished up CSS for the Hero image and the adjacent items
> Finish CSS for HomeImage

- client/src/components/ArticleCard/ArticleCard.css
- client/src/components/ArticleCard/ArticleCard.jsx
- client/src/components/ArticleCards/ArticleCards.css
- client/src/components/ArticleCards/ArticleCards.jsx
- client/src/components/Buying/Buying.css
- client/src/screens/Home/Home.jsx
Completed code for the article cards. This are rendered on the home page and have clickable links that should take the user to the article detail page. Need to make sure that the link is correct when routing in App.js
> Added code to article components, and added CSS styling

- client/src/screens/ArticleDetail/ArticleDetail.css
- client/src/screens/ArticleDetail/ArticleDetail.jsx
Detail page react/js and some css
> Dl feature articledetail

- client/src/App.js
- client/src/components/Article/Article.css
- client/src/components/Article/Article.jsx
- client/src/components/ArticleCards/ArticleCards.jsx
- client/src/screens/ArticleCreate/ArticleCreate.css
- client/src/screens/ArticleCreate/ArticleCreate.jsx
- client/src/screens/Articles/Articles.css
- client/src/screens/Articles/Articles.jsx
- client/src/screens/Home/Home.jsx
- controllers/articles.js
This is a big boi. I made the ARTICLES screen, ARTICLECREATE, and ARTICLE Component. I was getting confused with architecture and just pushed through. However, I went through and modified more than one file. POST works. Styling needed. Placeholder text isn't showing. We need to update Homepage (updated text on article) to actually grab the 'update data from database'. App is updated with more imports, components and Switch. I may have edited controllers for POST but it's working properly.
> Updating ArticleCreate and created Articles and Article

- client/src/App.js
- client/src/components/Article/Article.jsx
- client/src/screens/Articles/Articles.jsx
> Merge weekend components

- client/src/App.js
- client/src/components/Options/Options.css
- client/src/components/Options/Options.jsx
- client/src/screens/ArticleDetail/ArticleDetail.css
- client/src/screens/ArticleDetail/ArticleDetail.jsx
- client/src/screens/ArticleEdit/ArticleEdit.jsx
CRUD functionality pretty much there
> Sd article edit

- client/src/components/shared/Nav/Nav.jsx
Completed the routing back to the home page when clicking on the GreenHouse Logo. Also updated inline styling to remove the inherited link styling.
> Home Routing from the Title Complete

- client/src/components/Article/Article.css
- client/src/components/Article/Article.jsx
- client/src/screens/Articles/Articles.css
Styling for the article page has been updated
> Updated CSS Styling for the Article page

- client/src/screens/Articles/Articles.jsx
Added button with styling to take you to add article
> Button complete for the Add Article

- client/src/screens/ArticleDetail/ArticleDetail.css
- client/src/screens/ArticleEdit/ArticleEdit.css
- client/src/screens/ArticleEdit/ArticleEdit.jsx
> Update article edit CSS

- client/src/components/ArticleCards/ArticleCards.css
- client/src/components/Buying/Buying.css
- client/src/components/ChatHomePage/ChatHomePage.css
On hover changes the text color in buttons from white to orange.
> on hover completed for buttons

- client/src/screens/ArticleEdit/ArticleEdit.css
- client/src/screens/ArticleEdit/ArticleEdit.jsx
Finally done with this one....for now
> Finish CSS Article Edit

- client/src/components/Buying/Buying.css
- client/src/components/shared/Footer/Footer.css
Footer css styling is complete!
> Mobile styling for the footer complete

- client/src/components/HomeImage/HomeImage.css
- client/src/screens/Home/Home.css
> Fix landing page

- client/src/components/Article/Article.css
- client/src/components/ArticleCards/ArticleCards.css
- client/src/screens/Articles/Articles.css
updated the article styling for the mobile screens
> Article CSS styling complete

- client/src/components/HomeImage/HomeImage.css
- client/src/screens/ArticleDetail/ArticleDetail.css
Hero image and text CSS for mobile
> Adjust styling for mobile devices for Home Image

- client/src/components/shared/Nav/Nav.css
- client/src/screens/ArticleEdit/ArticleEdit.jsx
> Fix warning instead

- client/src/App.js
- client/src/components/shared/Nav/Nav.jsx
- client/src/screens/Dashboard/Dashboard.jsx
Link and routing complete for the dashboard.
> Added the dashboard link and routing from the homepage

- client/src/App.js
- client/src/components/shared/Nav/Nav.jsx
- client/src/screens/Dashboard/Dashboard.jsx
Reverts suttondemlong/green-house#50
> Revert "Revert "Added the dashboard link and routing from the homepage""

- client/src/components/ArticleCards/ArticleCards.css
- client/src/components/Badges/Badges.css
- client/src/components/Buying/Buying.css
- client/src/components/ChatHomePage/ChatHomePage.css
- client/src/components/Equipment/Equipment.css
- client/src/components/MyEquipmentRooms/MyEquipmentRooms.css
- client/src/components/MyRooms/MyRooms.css
- client/src/components/Reviews/Reviews.css
- client/src/components/RoomsEquipment/RoomsEquipment.css
- client/src/components/UserInformation/UserInformation.css
- client/src/components/UserInformation/UserInformation.jsx
- client/src/components/Wishlist/Wishlist.css
buttons are now smaller for mobile. Set size below 500px for media query.
> Updated the button components for mobile

- client/src/screens/MyEquipment/MyEquipment.jsx
Changed the function name and pathnames
> Updated my equipment screen to reflect naming convention change

- client/src/App.js
- client/src/components/Equipment/Equipment.jsx
- client/src/components/MyEquipment/MyEquipment.css
- client/src/components/MyEquipment/MyEquipment.jsx
- client/src/screens/Equipments/Equipments.jsx
Added the equipment screen off of the dashboard. Images still need to be styled however the link to the detail page is working.
> added equipment screen with equipment images

- client/src/App.css
- client/src/components/ArticleCards/ArticleCards.css
- client/src/components/ArticleCards/ArticleCards.jsx
- client/src/components/Badges/Badges.css
- client/src/components/Badges/Badges.jsx
- client/src/components/Buying/Buying.css
- client/src/components/Buying/Buying.jsx
- client/src/components/ChatHomePage/ChatHomePage.css
- client/src/components/ChatHomePage/ChatHomePage.jsx
- client/src/components/MyEquipment/MyEquipment.jsx
- client/src/components/MyRooms/MyRooms.jsx
- client/src/components/Options/Options.jsx
- client/src/components/Reviews/Reviews.css
- client/src/components/Reviews/Reviews.jsx
- client/src/components/RoomsEquipment/RoomsEquipment.jsx
- client/src/components/Savings/Savings.css
- client/src/components/Savings/Savings.jsx
- client/src/components/Stats/Stats.css
- client/src/components/Stats/Stats.jsx
- client/src/components/Wishlist/Wishlist.jsx
- client/src/components/shared/Nav/Nav.jsx
All buttons except for the ones on the user page now follow the same CSS. Basic-button CSS located in App.CSS
> Sd dash save

- client/src/components/Equipment/Equipment.css
- client/src/components/Equipment/Equipment.jsx
- client/src/screens/Equipments/Equipments.css
- client/src/screens/Equipments/Equipments.jsx
equipment screen is updated with functional css
> Gl feature equipmentscreen

- client/src/components/Badges/Badges.css
- client/src/components/Badges/Badges.jsx
- client/src/components/Savings/Savings.css
- client/src/components/Savings/Savings.jsx
- client/src/components/Stats/Stats.jsx
- client/src/components/shared/Layout/Layout.css
- client/src/screens/Home/Home.css
Everything but the breakpoints and the gauge
> Stats CSS except guage

- client/src/App.css
- client/src/components/Badges/Badges.css
- client/src/components/Savings/Savings.css
- client/src/components/Savings/Savings.jsx
- client/src/components/Stats/Stats.css
> Minor touches, media query still needed

- client/src/components/Search/Search.css
- client/src/components/Search/Search.jsx
- client/src/screens/Equipments/Equipments.jsx
- client/src/utils/sort.js
search function is now working with conditional rendering on the page
> Gl feature search

- client/src/components/Password/Password.jsx
- client/src/components/Savings/Savings.css
- client/src/components/SimilarItemsProducts/SimilarItemsProducts.css
- client/src/components/SimilarItemsProducts/SimilarItemsProducts.jsx
- client/src/components/SocialMedia/SocialMedia.css
- client/src/components/SocialMedia/SocialMedia.jsx
- client/src/components/Sort/Sort.css
- client/src/components/Sort/Sort.jsx
- client/src/components/Stats/Stats.css
- client/src/components/Stats/Stats.jsx
- client/src/components/UserInformation/UserInformation.css
- client/src/components/UserVerification/UserVerification.jsx
- client/src/components/shared/Footer/Footer.jsx
- client/src/screens/Equipments/Equipments.jsx
- client/src/screens/MyAccount/MyAccount.jsx
updated the userpage, still have quite a bit more css to go. Also updated CSS for the savings media query as well as similar products.
> Gl feature userpage

- client/src/components/Sort/Sort.css
- client/src/components/Sort/Sort.jsx
- client/src/screens/Equipments/Equipments.jsx
sort component is working and the number of results is dynamically changing on the page.
> Sort component completed

- client/src/components/Badges/Badges.css
- client/src/components/HomeImage/HomeImage.css
- client/src/components/Savings/Savings.css
- client/src/components/Stats/Stats.css
Fixed the hero image and the mobile breakpoints for Stats
> Sd hero image margin fix

- client/src/components/Password/Password.css
- client/src/components/Password/Password.jsx
- client/src/components/SocialMedia/SocialMedia.css
- client/src/components/SocialMedia/SocialMedia.jsx
- client/src/components/UserVerification/UserVerification.css
- client/src/components/UserVerification/UserVerification.jsx
styling for the user page is now complete
> css styling complete for user component

- client/src/components/shared/Nav/Nav.css
- client/src/components/shared/Nav/Nav.jsx
PLEASE LET ME SHOW LOCALLY BEFORE MERGING
> Fixing search bar to responsive div

- client/src/components/shared/Layout/Layout.css
- client/src/components/shared/Nav/Nav.css
- client/src/components/shared/Nav/Nav.jsx
Dean and I troubleshooted the Nav component, made some minor styling changes. Still not visable in Safari.
> Minor adjustments to Nav structure and CSS

- client/src/components/SignUp/SignUp.jsx
> fix is corrected for creating a user

- client/src/App.js
- client/src/components/LoginForm/LoginForm.css
- client/src/components/LoginForm/LoginForm.jsx
- client/src/components/LoginUser/LoginUserContext.jsx
- client/src/components/SignUp/SignUp.jsx
- client/src/components/shared/Nav/Nav.jsx
- client/src/screens/Dashboard/Dashboard.jsx
- client/src/screens/Login/Login.css
- client/src/screens/Login/Login.jsx
- client/src/services/users.js
- controllers/users.js
- routes/users.js
> Gl dl feature login

- client/src/App.css
- client/src/components/Badges/Badges.css
- client/src/components/Badges/Badges.jsx
- client/src/components/MyEquipment/MyEquipment.css
- client/src/components/Savings/Savings.css
- client/src/components/Savings/Savings.jsx
- client/src/components/shared/Layout/Layout.css
- client/src/components/shared/Nav/Nav.css
- client/src/components/shared/Nav/Nav.jsx
- client/src/screens/ArticleCreate/ArticleCreate.jsx
- client/src/screens/ArticleDetail/ArticleDetail.css
- client/src/screens/ArticleDetail/ArticleDetail.jsx
- client/src/screens/ArticleEdit/ArticleEdit.jsx
- client/src/screens/Articles/Articles.jsx
- client/src/screens/EquipmentDetail/EquipmentDetail.css
Cleaned up most of the UX team's feedback
> Sd ux css fixes

- client/src/components/Password/Password.css
- client/src/components/Password/Password.jsx
- client/src/components/SocialMedia/SocialMedia.css
- client/src/components/SocialMedia/SocialMedia.jsx
- client/src/components/UserInformation/UserInformation.css
- client/src/components/UserInformation/UserInformation.jsx
- client/src/components/UserVerification/UserVerification.css
- client/src/components/UserVerification/UserVerification.jsx
- client/src/screens/MyAccount/MyAccount.jsx
This is the user page that I believe is completed more or less. CRUD to still be implemented. Attempted PUT for password shows 200 status but it doesn't grab it. Password validator placed.
> Am feature i3

- client/src/components/LoginForm/LoginForm.css
- client/src/components/LoginForm/LoginForm.jsx
- client/src/components/SignUp/SignUp.css
- client/src/components/SignUp/SignUp.jsx
> Styling of login and signup

- client/src/components/SocialMedia/SocialMedia.jsx
> Delete User Request is now working

- client/src/components/SignUp/SignUp.jsx
- client/src/components/SocialMedia/SocialMedia.jsx
- client/src/components/Sort/Sort.jsx
- client/src/screens/Equipments/Equipments.jsx
updated the delete request and updated the sort drop downs to reflect savings instead of price
> Updated sort drop downs and updated the delete request

- client/src/components/HomeImage/HomeImage.css
- client/src/components/shared/Nav/Nav.css
> Hero image, nav bar

- client/src/App.js
- client/src/components/UserVerification/UserVerification.jsx
- client/src/screens/EditUserInfo/EditUserInfo.css
- client/src/screens/EditUserInfo/EditUserInfo.jsx
> Sd edit info

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/LoginForm/LoginForm.jsx
- client/src/components/LoginUser/LoginUserContext.jsx
- client/src/components/UserVerification/UserVerification.jsx
- client/src/screens/Dashboard/Dashboard.jsx
- client/src/screens/EditUserInfo/EditUserInfo.jsx
- client/src/services/users.js
> Sd local storage

- client/src/components/EditImageComp/EditImageComp.jsx
- client/src/components/EditImageComp/EditimageComp.css
> edited name of CSS file

- client/src/components/LoginUser/LoginUserContext.jsx
> localUser taken out of useEffect

- client/src/components/EditImageComp/EditImageComp.jsx
- client/src/components/Password/Password.jsx
- client/src/components/Sort/Sort.css
- client/src/screens/EditUserInfo/EditUserInfo.jsx
updated changes to the my account screen for reload and also updated the sort bar.
> Gl feature pagereload

- client/src/components/LoginForm/LoginForm.css
- client/src/components/LoginForm/LoginForm.jsx
- client/src/components/LoginUser/LoginUserContext.jsx
- client/src/components/Password/Password.jsx
- client/src/screens/Dashboard/Dashboard.css
- client/src/screens/Dashboard/Dashboard.jsx
- client/src/screens/EditUserInfo/EditUserInfo.jsx
> Deploy after hot hot hot fixes

- client/src/components/EditImageComp/EditImageComp.jsx
- client/src/components/LoginForm/LoginForm.jsx
- client/src/components/LoginUser/LoginUserContext.jsx
- client/src/components/Password/Password.jsx
- client/src/components/SocialMedia/SocialMedia.jsx
- client/src/components/UserInformation/UserInformation.jsx
- client/src/components/UserVerification/UserVerification.jsx
- client/src/screens/Dashboard/Dashboard.jsx
- client/src/screens/EditUserInfo/EditUserInfo.jsx
> Update UseContext Functionality

- client/src/components/shared/Layout/Layout.css
Styling is fixed for safari nav bar
> Updated styling for Safari

- client/public/index.html
completed the image meta data for the project.
> updated img url for meta data
